/**
 * Easebuzz Payment Gateway TypeScript Interfaces
 *
 * This file contains all the TypeScript interfaces and types needed for
 * integrating with the Easebuzz payment gateway.
 */

/**
 * Payment Status Enums
 */
export enum EasebuzzPaymentStatus {
  SUCCESS = "success",
  FAILURE = "failure",
  PENDING = "pending",
  CANCELLED = "cancelled",
  REFUNDED = "refunded",
}

/**
 * Easebuzz Environment Types
 */
export type EasebuzzEnvironment = "test" | "prod";

/**
 * Easebuzz Initiate Payment Request Interface
 *
 * Required fields for initiating a payment with Easebuzz
 */
export interface EasebuzzInitiateRequest {
  /** Merchant key provided by Easebuzz */
  key: string;

  /** Unique transaction ID generated by merchant */
  merchant_txn: string;

  /** Transaction amount in smallest currency unit (e.g., paise for INR) */
  amount: number;

  /** Customer's first name */
  firstname: string;

  /** Customer's email address */
  email: string;

  /** Customer's phone number */
  phone: string;

  /** Product information */
  product_info: string;

  /** Success URL - where to redirect after successful payment */
  surl: string;

  /** Failure URL - where to redirect after failed payment */
  furl: string;

  /** Currency code (e.g., "INR") */
  currency?: string;

  /** Customer's last name */
  lastname?: string;

  /** Customer's address */
  address1?: string;

  /** Customer's city */
  city?: string;

  /** Customer's state */
  state?: string;

  /** Customer's country */
  country?: string;

  /** Customer's postal code */
  zipcode?: string;

  /** Customer's unique ID */
  udf1?: string;

  /** Additional custom field 1 */
  udf2?: string;

  /** Additional custom field 2 */
  udf3?: string;

  /** Additional custom field 3 */
  udf4?: string;

  /** Additional custom field 4 */
  udf5?: string;

  /** Payment gateway mode (e.g., "CC", "DC", "NB", "UPI") */
  pg?: string;

  /** Bank code for specific payment method */
  bankcode?: string;

  /** Transaction type */
  txnid?: string;

  /** Hash value for security validation */
  hash?: string;
}

/**
 * Easebuzz Initiate Payment Response Interface
 *
 * Response received when initiating a payment
 */
export interface EasebuzzInitiateResponse {
  /** Response status */
  status: string;

  /** Response data containing payment details */
  data: {
    /** Access key for payment gateway */
    access_key: string;

    /** Payment gateway URL */
    pg_url: string;

    /** Transaction ID */
    txnid: string;

    /** Merchant transaction ID */
    merchant_txn: string;

    /** Transaction amount */
    amount: number;

    /** Currency code */
    currency: string;

    /** Customer email */
    email: string;

    /** Customer phone */
    phone: string;

    /** Product information */
    product_info: string;

    /** Success URL */
    surl: string;

    /** Failure URL */
    furl: string;

    /** Hash value for validation */
    hash: string;
  };

  /** Error message if any */
  error?: string;

  /** Error code if any */
  error_code?: string;
}

/**
 * Easebuzz Callback Response Interface
 *
 * Response received in the callback/webhook from Easebuzz
 */
export interface EasebuzzCallbackResponse {
  /** Transaction ID from Easebuzz */
  txnid: string;

  /** Merchant transaction ID */
  merchant_txn: string;

  /** Transaction amount */
  amount: number;

  /** Payment status */
  status: EasebuzzPaymentStatus;

  /** Hash value for validation */
  hash: string;

  /** Payment gateway used */
  pg?: string;

  /** Bank code if applicable */
  bankcode?: string;

  /** Error message if payment failed */
  error?: string;

  /** Error code if payment failed */
  error_code?: string;

  /** Customer email */
  email?: string;

  /** Customer phone */
  phone?: string;

  /** Product information */
  product_info?: string;

  /** Currency code */
  currency?: string;

  /** Additional custom field 1 */
  udf1?: string;

  /** Additional custom field 2 */
  udf2?: string;

  /** Additional custom field 3 */
  udf3?: string;

  /** Additional custom field 4 */
  udf4?: string;

  /** Additional custom field 5 */
  udf5?: string;
}

/**
 * Easebuzz Transaction Status Response Interface
 *
 * Response received when checking transaction status
 */
export interface EasebuzzTransactionStatusResponse {
  /** Response status */
  status: string;

  /** Transaction details */
  data: {
    /** Transaction ID */
    txnid: string;

    /** Merchant transaction ID */
    merchant_txn: string;

    /** Transaction amount */
    amount: number;

    /** Payment status */
    status: EasebuzzPaymentStatus;

    /** Payment gateway used */
    pg: string;

    /** Bank code if applicable */
    bankcode?: string;

    /** Error message if any */
    error?: string;

    /** Error code if any */
    error_code?: string;

    /** Transaction date */
    date?: string;

    /** Customer email */
    email?: string;

    /** Customer phone */
    phone?: string;

    /** Product information */
    product_info?: string;

    /** Currency code */
    currency?: string;
  };

  /** Error message if any */
  error?: string;

  /** Error code if any */
  error_code?: string;
}

/**
 * Easebuzz Refund Request Interface
 *
 * Required fields for refunding a payment
 */
export interface EasebuzzRefundRequest {
  /** Merchant key */
  key: string;

  /** Transaction ID to refund */
  txnid: string;

  /** Refund amount */
  amount: number;

  /** Refund reason */
  reason?: string;

  /** Hash value for validation */
  hash: string;
}

/**
 * Easebuzz Refund Response Interface
 *
 * Response received when processing a refund
 */
export interface EasebuzzRefundResponse {
  /** Response status */
  status: string;

  /** Refund details */
  data: {
    /** Refund ID */
    refund_id: string;

    /** Original transaction ID */
    txnid: string;

    /** Refund amount */
    amount: number;

    /** Refund status */
    status: EasebuzzPaymentStatus;

    /** Refund reason */
    reason?: string;

    /** Refund date */
    date?: string;
  };

  /** Error message if any */
  error?: string;

  /** Error code if any */
  error_code?: string;
}

/**
 * Easebuzz Configuration Interface
 *
 * Configuration object for Easebuzz integration
 */
export interface EasebuzzConfig {
  /** Merchant key */
  merchantKey: string;

  /** Salt key for hash generation */
  salt: string;

  /** Environment (test/prod) */
  environment: EasebuzzEnvironment;

  /** Base URL for API calls */
  baseUrl: string;

  /** Success URL template */
  successUrl: string;

  /** Failure URL template */
  failureUrl: string;
}

/**
 * Easebuzz Payment Method Types
 */
export type EasebuzzPaymentMethod =
  | "CC" // Credit Card
  | "DC" // Debit Card
  | "NB" // Net Banking
  | "UPI" // UPI
  | "WALLET" // Digital Wallet
  | "EMI"; // EMI

/**
 * Easebuzz Bank Codes
 */
export interface EasebuzzBankCodes {
  /** Credit Card */
  CC: string[];

  /** Debit Card */
  DC: string[];

  /** Net Banking */
  NB: string[];

  /** UPI */
  UPI: string[];

  /** Digital Wallet */
  WALLET: string[];

  /** EMI */
  EMI: string[];
}
